name: Staging

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        # run: npm ci
        run: yarn install --frozen-lockfile # --production

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build --if-present

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGING }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          args: deploy --dir=./public --prod --message \" $(git log -1 --pretty=format:%B) \"
          # args: deploy --dir=./public --prod --open --message \" $(git log --oneline -n) \"
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID_STAGING"]'

      - name: Logs for Netlify
        uses: bdougie/loglify@v1.0.0
